- name: Install Longhorn
  hosts: master
  #become: true
  gather_facts: false
  tasks:

# trying with ansible native 
    - name: Add stable chart repo
      kubernetes.core.helm_repository:
        validate_certs: false
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        #force_update: true
        repo_name: longhorn
        repo_url: "https://charts.longhorn.io"
        state: present

    - name: helm repo update
      kubernetes.core.helm:
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        state: absent
        release_name: dummy # tricks needed to refresh in separate step
        release_namespace: kube-system
        update_repo_cache: true

    - name: Deploy Container-agent
      kubernetes.core.helm:
        validate_certs: false
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        name: longhorn
        chart_ref: longhorn/longhorn
        create_namespace: true
        release_namespace: longhorn-system
        release_state: present
        purge: true
        force: true
        wait: true
        set_values:
          - value: defaultSettings.defaultDataPath="/storage"
            value_type: string
          - value: service.ui.loadBalancerIP="192.168.100.182"
            value_type: string
          - value: service.ui.type="LoadBalancer"
            value_type: string
